travis:
  secure:
    BINSTAR_TOKEN: m62gTc0d5lBqi9CA4X/SnSgFzOrHrFaWFzEda8/sDPKHNwslxzUCEF422jZ9HIW1vUgIz4a78+Vk/KBHzJBzixcoUC6XJgs1Id4Q4TCApdt82VYnjBJC7POHTbtWIn1N/2lUcsK3loMSMLkT87WvectsvVN42SgRF3q26Oq3D6Ws4fYA1bByI/dHHPf9vs2rqb1504rijP9riHcEf7/AnqPSGDgyhHfW1k85xsUV+EScwz7cNoogMsb4i61BXzpRYqHwZ8uZM4YUciRsV64EtdHRrtFKY3xmUHe91ZbrjwnqF6is4lPsTAMf29PXX4L1LN9v+AKndGjUYQ4PAExi0lcH9kCyH5KbhNGBh7JT4pO3t+hciyXUO4kgj3sHbN98YmQy7loinxForVNfR6ppHdBDdYRGTMoxuFz5eiOQXscA8BvUMvow71rWFKV9WlfZFXtToQhrzZ/+qQGIsXaKY5dP4gSh/n5/tp82k+t3atGwjRLDkxgxCS2PuZNcydVjpZTyZE+vOEaeKuUhRFe64IEctdUhQd2EXQvGYrqVCBrcGEnvQxGM8TjjbU/DS0niFJngHOJFQb3J4UVTib5DVH8ZldbhZmQisNeC0MfAu4fo+3FDsspt1uDvTguPNV8JjdmbrBfhqntk7mN2wX/DNq81SXbmM5vjkz06ri0VSP0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
