travis:
  secure:
    BINSTAR_TOKEN: 1VRj4CMn2pQgiQ5FkiQdbCeetBtRhraKBtcvmnoeLMIedFIpD+ZUg7nmAOiCmA4Q1MEys5rt3Z2dGI44CW8AkWXFoshxQHb6ZiF+LhbXT/2gyrj7uxCTxHW2Fr4BNrXXjaa+PYL9cupiHuff8EZHsx9gOHYQ0Mczpj/xwO+xPnJoxkrfi+WgyFDCyLF5Q+Ote8Jo5duP1KczQJxa6Ginb1fof3b+Xqe/32PCT6GnhtppgaRjyBhnqv4axC0srlh4GiUXY8ZFGLTbMznVjoEiNtB90/HJBpH+oZIYlCHeQ80EsEEMo5J11xpGyZytn3MI71MhtnIHU44A+Pk8Rbnzz6+mdzL+NH6gWcEZjirix2g6kYAueSmBndk027lxAXHE+es2VfYwlvWK0h0At3Z8GU80W26yd3T+9Y95Mti+BZuaRt8S5u6nw2PkhMFip4s3mnfhfcAwBpy/Dsugmh5fncp9/bArbSdT6z+qX4IYYgZQbvFYMhch5z37WOooa94/kJT+me3AQd3svnYiHvcxliJtcsCtQYLL5V4K76atNSo1tGKOuBGIlfmxkM+SMitidbdC9lGm0NbAAJLfmGEm5xfU71KrGRTShuFqFTrw08ufXJOypHLk7dl/8xnF8egKaJ2c1RgszG8Tyy1fbtXL/19zfeGxOQU4rQviX/wO6WA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
